#!/usr/bin/env bash
# a script that configures a new Ubuntu machine to respect the specified requirements
# (this script will be run on the server itself)
# Installs nginx and configures it on a remote server

# Update package lists and install nginx
apt-get -y update
apt-get -y install nginx

# Configure firewall to allow Nginx HTTP traffic
ufw allow 'Nginx HTTP'

# Create a custom index file with "Hello World!" message
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Start nginx service
service nginx start
