#!/usr/bin/env bash
# a script that generates a MySQL dump and creates a compressed archive of it.
# Set the password for the MySQL root user
MYSQL_PASSWORD="$1"

# Get the current date
CREATED_FILE="$(date +"%d-%m-%Y").tar.gz"

# Dump the MySQL databases
mysqldump --user=root --password="${MYSQL_PASSWORD}" --all-databases > backup.sql

# Compress the dump file to a tar.gz archive
tar -czvf "$CREATED_FILE" "backup.sql"
