#!/usr/bin/env bash
# a script that rete a symbolic link for Nginx configuration file, starts Nginx service, and then stops the first running Nginx process. Nginx listens on port 80 still.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
