#!/usr/bin/env bash
# a script that displays a list of current running processes.
# show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

echo "List of currently running processes:"
ps -axjf
