#!/usr/bin/env bash
# Write a manage_my_process Bash script that:
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds
# Write Bash (init) script 101-manage_my_process that manages manage_my_process.
# (both files need to be pushed to git)

case "$1" in
    start)
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        echo "manage_my_process stopped"
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        ;;
    restart)
        echo "manage_my_process restarting"
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
esac
