#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code, and displays this data.

awk '{count[$1 " " $9]++} END {for (i in count) print count[i], i}' apache-access.log | sort -rn
