#!/usr/bin/env bash
# a script that installs the ufw firewall and setup a few rules on web-01.
# Configures a ufw firewall to block all incoming traffic except for TCP ports 22, 443, and 80.

apt-get update
apt-get install ufw -y
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw --force disable
ufw --force enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
