#!/usr/bin/env bash
# a script that configures the container to make Nginx run as Nginx, and listening port on 8080
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
